# Theme setting
theme: jekyll-theme-hacker

timezone: Etc/GMT-8

# Site settings
title: S0N9
SEOTitle: S0N9 | Song Ye's personal website
description: "Hello, world! This is Song Ye's personal website."
keyword: "Song Ye, SONG YE'S, S0N9"

