# Site settings
title: S0N9 | Welcome to S0N9.COM
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://s0n9.com"
author:
  name: "S0N9Y3"
  email: "y3@s0n9.com"
  url: "http://s0n9.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
